/**
 * prompt-parser.js
 *
 * Parse prompts.md files generated by PromptWriter.writePromptsFile().
 * Extracted so it can be reused by BrowserImageGenerator and other tools.
 *
 * Format parsed:
 *   ### 📌 Phân cảnh N: Title
 *   **--- Ảnh X (label) ---**
 *   * **Tên file:** `filename.png`
 *   * **🚀 Prompt:**
 *   ```text
 *   ...prompt content...
 *   ```
 */

class PromptParser {
    static parseFile(filePath) {
        const fs = require('fs');
        const content = fs.readFileSync(filePath, 'utf-8');
        return PromptParser.parseContent(content);
    }

    static parseContent(content) {
        const lines = content.split('\n');
        const prompts = [];
        let sectionName = null;
        let currentName = null;
        let currentPrompt = '';
        let inCodeBlock = false;
        let currentFile = '';

        for (const line of lines) {
            const sectionMatch = line.match(/^#{2,3}\s*📌?\s*Phân cảnh\s*\d+[a-z]?\s*:\s*(.+)/i);
            if (sectionMatch) {
                PromptParser._flush(currentName, currentPrompt, currentFile, prompts);
                sectionName = sectionMatch[1].trim();
                currentName = null;
                currentPrompt = '';
                currentFile = '';
                inCodeBlock = false;
                continue;
            }

            const subImageMatch = line.match(/^\*{2,3}---\s*Ảnh\s*([A-ZÉ])\s*.*---\s*\*{2,3}/i);
            if (subImageMatch) {
                PromptParser._flush(currentName, currentPrompt, currentFile, prompts);
                currentName = sectionName
                    ? `${sectionName} (Ảnh ${subImageMatch[1]})`
                    : `(Ảnh ${subImageMatch[1]})`;
                currentPrompt = '';
                currentFile = '';
                inCodeBlock = false;
                continue;
            }

            const fileMatch = line.match(/`([^`]+\.png)`/);
            if (fileMatch && !currentFile) {
                currentFile = fileMatch[1];
                continue;
            }

            if (line.trim() === '```text') { inCodeBlock = true; continue; }
            if (line.trim() === '```') { inCodeBlock = false; continue; }
            if (inCodeBlock) { currentPrompt += line + '\n'; }
        }

        PromptParser._flush(currentName, currentPrompt, currentFile, prompts);
        return prompts;
    }

    static fromSegments(segments, lang = 'vi') {
        const prompts = [];
        segments.forEach((seg, index) => {
            const stt = index + 1;
            const slug = seg.title
                ? seg.title.toLowerCase().replace(/\s+/g, '_').replace(/[^a-z0-9_]/g, '')
                : `segment_${stt}`;

            // Accept both seg.prompts (plain string map) and seg.images (object map from generate_prompts)
            const rawPrompts = seg.prompts || seg.images || {};
            const labelKeys = Object.keys(rawPrompts);
            labelKeys.forEach(key => {
                const entry = rawPrompts[key];
                if (!entry) return;
                // entry can be a string (direct prompt text) or an object { prompt: '...', filename: '...' }
                const promptText = typeof entry === 'string' ? entry : entry.prompt;
                if (!promptText) return;
                const fileName = `${stt}_${slug}_${key}.png`;
                prompts.push({
                    name: `${seg.title || ''} (Ảnh ${key.toUpperCase()})`,
                    file: fileName,
                    prompt: promptText,
                });
            });
        });
        return prompts;
    }

    static _flush(name, prompt, file, prompts) {
        if (name && prompt) {
            prompts.push({ name, file: file || '', prompt: prompt.trim() });
        }
    }
}

module.exports = PromptParser;
